### ISSUE TITLE
Empty error being thrown while purchasing an event

### ISSUE THREAD

**Issue by Shirkit** [HasteDesign/Registrations-for-WooCommerce#13]
https://www.orquidariobahia.com.br/produto/curso-basico-orquideas/

While trying to purchase a registration (linked above), after filling the billing info, it throws an empty error. It works fine with other products (I've disable the purchase for other products in that website since it's a catalog only for the moment, but I temporarily enabled and it does purchase with other products).

I do now know what's throwing the error, I've tried with different Payment Gateways (Pagseguro, Paypal and Check) and I've also tried to disable caching and other plugins that might conflict, but no luck, the error is still a blank error.

I do not know how to proceed, since no logs are being written in the WooCommerce logs.

Can you give me a hand @allysonsouza ?

**Comment by Shirkit** [comment]
I tried debugging to no luck, I can't figure it out what's causing the bug. Maybe the database is in a point which it corrupted the plugin? I can't see any other possible cause to that empty error.

**Comment by allysonsouza** [comment]
Hi @Shirkit,

Sorry for not being able to reply earlier, I was very busy in the last weeks. You are using WooCommerce 3.0? I started a branch to make the fixes to WC 3.*, and looks like a lot of thing need changes, improvements, maybe it's some incompatibility.

In your debug.log there's nothing being registered?

**Comment by Shirkit** [comment]
I'm using WooCommerce 2.6.14. I do not know where's a debug.log, I only see an empty test.log in my uploads/wc-logs folder, and nothing else.

**Comment by allysonsouza** [comment]
In wp-content/ folder there's a `debug.log` file, if debug constants are defined in your `wp-config.php`.
Check if these constants are set in your install, so errors would be logged.

[Debugging in WordPress](https://codex.wordpress.org/Debugging_in_WordPress)

**Comment by Shirkit** [comment]
Did as you said and found the bug, created the PR #14 to solve it.
