### ISSUE TITLE
When press variations, nothing appears.

### ISSUE THREAD

**Issue by fkkm1999** [HasteDesign/Registrations-for-WooCommerce#16]
When i try to add the variations just a blank space appears? And i cannot set anything? Screenshot:  http://imgur.com/a/31qXT

**Comment by allysonsouza** [comment]
Hi @fkkm1999,

What happens when you click on **Ga** button, whit 'Variatie toevoegen' selected?

**Comment by fkkm1999** [comment]
That did the job thank you!
