### ISSUE TITLE
Site fica Off-Line ao Ativar o Plugin 

### ISSUE THREAD

**Issue by Claudivan-Menezes** [HasteDesign/Registrations-for-WooCommerce#2]
Olá o plugin Registrations-for-WooCommerce deixa meu site offline toda vez que eu ativo, podem por favor me ajudar com isso ?

**Comment by allysonsouza** [comment]
Olá @Claudivan-Menezes,

O seu servidor possui PHP 5.3 ou superior? Se sim, você pode ativar o debug do seu WordPress e me dizer que mensagens de erro ele está exibindo?

**Comment by Claudivan-Menezes** [comment]
Olá Allyson, 
A versão do php é superior a 5.3.....
Deu esse erros que devem ser refentes ao plugin:

Warning: require_once() [function.require-once]: Unable to allocate memory for pool. in /wp-content/plugins/Registrations-for-WooCommerce-master/registrations-for-woocommerce.php on line 172

Warning: include_once() [function.include-once]: Unable to allocate memory for pool. in /wp-content/plugins/woocommerce/includes/class-wc-autoloader.php on line 56

Parse error: syntax error, unexpected '[' in /wp-content/plugins/Registrations-for-WooCommerce-master/classes/class-wc-registrations-checkout.php on line 140

**Comment by allysonsouza** [comment]
Olá @Claudivan-Menezes ,

Os erros no `require_once` provavelmente são relacionados às configurações do seu PHP, como apontado nesta dúvida do StackOverflow: http://stackoverflow.com/a/3723338

Já o erro de sintaxe é porquê o plugin utiliza a versão curta de declaração de arrays, introduzida a partir do PHP 5.4, não funcionando em versões anteriores. Já há um bom tempo o WordPress recomendava PHP 5.6, e desde o início desse ano tem recomendado o PHP 7, então minha sugestão é procurar um servidor com uma versão atualizada do PHP. https://wordpress.org/about/requirements/

**Comment by Claudivan-Menezes** [comment]
De fato meu theme exigiu configurações diferenciadas antes de instalar tais como:
WP Memory Limit   Currently: 256M
Upload Max. Filesize   Currently: 250M
Max. Post Size   Currently: 250M
Max. Execution Time   Currently: 300
PHP Max. Input Vars   Currently: 2000
PHP Max. Input Time   Currently: 1000
Não sei si isso pode ter casado o require_once mais de qualquer forma vou atualizar o PHP do servidor e testar novamente.

Obrigado !!!

**Comment by Claudivan-Menezes** [comment]
Olá,
Mudei a Versão do PHP e o Plugin esta funcionando normalmente, Obrigado.
