### ISSUE TITLE
30 Variations Limit 

### ISSUE THREAD

**Issue by davidwood56** [HasteDesign/Registrations-for-WooCommerce#23]
I have a training site with venues and dates for the courses. We have 5 venues and different dates for each venue. Your plugin is really easy to use and we really like it. If you're able to resolve the issue below in your next update, it would be greatly appreciated.

When we get to 31 variations, all the dates for all the venues are displayed in the dropdown for each venue. At 30 and under only the dates available per venue are displayed which is what we want. So the course in the link below is displaying correctly because we are below the limit of 30.

This limit seems to coincide with two 'pages' in the WP editor (15 variations per 'page').

Can this limit be extended so we can add more than 30 variations and still have only the correct dates displayed?

https://www.learningworx.co.uk/product/emergency-first-aid-at-work-classroom/

Thanks for your help.

**Comment by allysonsouza** [comment]
Hi @davidwood56,

Thank you, we're happy you did a great job and our plugin helped you. I'll put this improvement in our tasks to the next releases! I'm sorry we're without time these months, but soon we'll come back to work and provide some improvements to the plugin!

**Comment by sebasgb92** [comment]
Hello,

I have the same issue when there are more than 30 variations woocommerce unlinck the attributes, I have brand and phone models as attibutes and I want to show just the phone models for the brand apple and the phone models for the brand Samsung when there are more than 30 variations woocommerce show all the models for apple and Samsung

**Comment by allysonsouza** [comment]
Hi @davidwood56 and @sebasgb92, I'm sorry it took almost a year, but I figured it's not a Registrations for WooCommerce issue, WooCommerce by default comes with the limite of 30 variations (to prevent Ajax issues). You can increase this number using the hook `woocommerce_ajax_variation_threshold`, like pointed in this article: https://elvtn.com/woocommerce/overridng-woocommerce-ajax-variations-limit/
