### ISSUE TITLE
days-of-the-week fields redundant?

### ISSUE THREAD

**Issue by ajlowndes** [HasteDesign/Registrations-for-WooCommerce#25]
I do not understand the reason for the "Days of Week when this event occurs" check-boxes in the variations edit panel. Since we have already put in a single, multiple or range of dates for the course to run, won't the days of the week simply be calculated, removing the need to manually input them? Or am I missing something?

Thanks,

**Comment by allysonsouza** [comment]
Hi @ajlowndes,

The `days of week` fields should be displayed only when you're using the range type, because you can set that your event will occur from March 2 to April 16, but in which days? You can define it will happen every friday and monday, for example.
