### ISSUE TITLE
Makes easily to add new checkout fields for each participant

### ISSUE THREAD

**Issue by allysonsouza** [HasteDesign/Registrations-for-WooCommerce#3]
Related support: https://wordpress.org/support/topic/adding-custom-checkout-fields/

At the moment it's not easy to add new checkout fields without override the entire function and rewrite it. The methods must have hooks that makes possible to extend/add/remove fields for participants in an easy way.

**Comment by Claudivan-Menezes** [comment]
Olá Allyson, 
Primeiro parabéns pelo plugin, Tenho uma duvida sobre o plugin gostaria de saber se é possível que os inscritos sejam vinculados na Ordem do pedido internamente no woocomerce ao invés de criar um usuário pra cada inscrição ? o plugin atual só vincula o cliente que faz o pagamento!

**Comment by allysonsouza** [comment]
Olá @Claudivan-Menezes,

O plugin atualmente lista nos detalhes do pedido quem são os inscritos, que podem ser diferentes do comprador, este sim usuário relacionado ao pedido. O WooCommerce trabalha com uma relação 1 para 1 entre pedidos e usuários, o que é o mais natural também.

Espero ter ajudado!

**Comment by allysonsouza** [comment]
Outra coisa @Claudivan-Menezes, agora que vi: crie sua própria issue para dúvidas, ou vá na página de suporte do plugin. Esta issue diz respeito a uma feature a ser implementada, irei apagar esses comentários assim que visualizá-los.

**Comment by Claudivan-Menezes** [comment]
Ok, obrigado !
