### ISSUE TITLE
Mutliple Times on same day

### ISSUE THREAD

**Issue by fcarentz** [HasteDesign/Registrations-for-WooCommerce#5]
Not an issue as much as a question. Is there an easy way to add multiple times to the same day?  Any assistance would be greatly appreciated

**Comment by allysonsouza** [comment]
Hi @fcarentz,

At the moment you can only set one start and one end time per date. I don't understand well the case to have multiple times per date, but what you can do is set multiple variations for each date, and set different times for each one.

I hope it helps!
